# Generated by Django 3.1.3 on 2020-12-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name_company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name_Currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name_Index', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaresData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name_ware', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wares_Last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateTimeField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Name_Ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.waresdata')),
            ],
        ),
        migrations.CreateModel(
            name='Wares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('Name_ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.waresdata')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes_last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateTimeField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField(blank=True, null=True)),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('Name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('Name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='Index_Last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateTimeField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Name_Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.indexdata')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('Name_Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.indexdata')),
            ],
        ),
        migrations.CreateModel(
            name='Currency_Last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateTimeField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Name_Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.currencydata')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Name_Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.currencydata')),
            ],
        ),
    ]
