# Generated by Django 3.1.3 on 2020-11-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_company', models.CharField(max_length=100)),
                ('Link_to_Search', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Volume', models.IntegerField()),
                ('Name_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.companydata')),
            ],
        ),
    ]
