# Generated by Django 3.1.3 on 2021-01-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0002_auto_20201205_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='Name_company',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Name_Currency',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='currency_last',
            old_name='Name_Currency',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='currencydata',
            old_name='Name_Currency',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Name_Index',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='index_last',
            old_name='Name_Index',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='indexdata',
            old_name='Name_Index',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='Name_company',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='quotes_last',
            old_name='Name_company',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='wares',
            old_name='Name_ware',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='wares_last',
            old_name='Name_ware',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='waresdata',
            old_name='Name_ware',
            new_name='Name',
        ),
    ]
