# Generated by Django 3.1.3 on 2021-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0003_auto_20210110_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_last',
            name='Change_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index_last',
            name='Change_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes_last',
            name='Change_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares_last',
            name='Change_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='Closing_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
