# Generated by Django 3.1.3 on 2021-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0004_auto_20210110_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency_last',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency_last',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index_last',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index_last',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes_last',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes_last',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares_last',
            name='RSI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares_last',
            name='Stochastic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
