# Generated by Django 3.1.3 on 2021-01-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0005_auto_20210110_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='av_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='av_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='av_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='av_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='av_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='av_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares',
            name='av_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wares',
            name='av_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
