# Generated by Django 3.1.3 on 2021-03-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0006_auto_20210125_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NC_Quotes_last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateTimeField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField(blank=True, null=True)),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('Change_price', models.FloatField(blank=True, null=True)),
                ('RSI', models.FloatField(blank=True, null=True)),
                ('Stochastic', models.FloatField(blank=True, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.ncdata')),
            ],
        ),
        migrations.CreateModel(
            name='NC_Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_trading', models.DateField()),
                ('Opening_price', models.FloatField()),
                ('Highest_price', models.FloatField()),
                ('Lowest_price', models.FloatField()),
                ('Closing_price', models.FloatField()),
                ('Volume', models.BigIntegerField(blank=True, null=True)),
                ('RSI', models.FloatField(blank=True, null=True)),
                ('av_gain', models.FloatField(blank=True, null=True)),
                ('av_loss', models.FloatField(blank=True, null=True)),
                ('Stochastic', models.FloatField(blank=True, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.ncdata')),
            ],
        ),
    ]
