# Generated by Django 3.1.3 on 2021-02-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='PLN', max_length=9),
        ),
    ]
