# Generated by Django 3.1.3 on 2021-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_cantor_exchange_rate_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transfer',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
