# Generated by Django 3.1.3 on 2021-02-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_bank_transfer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='currency_account_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_account_for', to='wallet.currency_account'),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='currency_account_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_account_to', to='wallet.currency_account'),
        ),
    ]
