# Generated by Django 3.1.3 on 2021-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20210211_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantor',
            old_name='cash',
            new_name='cash_for',
        ),
        migrations.AddField(
            model_name='cantor',
            name='cash_to',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
