# Generated by Django 3.1.3 on 2021-02-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_cantor_cash_after_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantor',
            old_name='day_exchange',
            new_name='day_transfer',
        ),
    ]
