# Generated by Django 3.1.3 on 2021-02-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WIG', '0006_auto_20210125_2126'),
        ('wallet', '0013_auto_20210220_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('day_transfer', models.DateField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.broker_account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.companydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='broker_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(blank=True, null=True)),
                ('title', models.TextField(blank=True, max_length=400, null=True)),
                ('cash_after', models.FloatField(blank=True, null=True)),
                ('cash_after_broker', models.FloatField(blank=True, null=True)),
                ('day_transfer', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency_account')),
                ('account_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.broker_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
