# Generated by Django 3.1.3 on 2021-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_stocks_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='PLN', max_length=9),
        ),
    ]
