# Generated by Django 3.1.3 on 2021-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_stocks_transfer_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='PLN', max_length=9),
        ),
        migrations.AddField(
            model_name='stocks_transfer',
            name='cash_after_broker',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
