# Generated by Django 3.1.3 on 2021-03-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WIG', '0007_nc_quotes_nc_quotes_last_ncdata'),
        ('wallet', '0018_auto_20210306_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='NC_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ammount', models.IntegerField(default=1)),
                ('cash_after_broker', models.FloatField(blank=True, null=True)),
                ('day_transfer', models.DateField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.broker_account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.ncdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.FloatField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='PLN', max_length=9)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.broker_account')),
                ('last_price', models.ForeignKey(default=447, on_delete=django.db.models.deletion.CASCADE, to='WIG.quotes_last')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIG.ncdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
