# Generated by Django 3.1.3 on 2021-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_nc_nc_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='nc',
            name='order',
            field=models.CharField(choices=[('Zakup', 'Zakup'), ('Sprzedarz', 'Sprzedarz')], default='Zakup', max_length=9),
        ),
        migrations.AddField(
            model_name='stocks',
            name='order',
            field=models.CharField(choices=[('Zakup', 'Zakup'), ('Sprzedarz', 'Sprzedarz')], default='Zakup', max_length=9),
        ),
    ]
