# Generated by Django 3.1.3 on 2021-03-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WIG', '0007_nc_quotes_nc_quotes_last_ncdata'),
        ('wallet', '0021_auto_20210318_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc',
            name='last_price',
            field=models.ForeignKey(default=447, on_delete=django.db.models.deletion.CASCADE, to='WIG.nc_quotes_last'),
        ),
    ]
