# Generated by Django 3.1.3 on 2020-11-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_auto_20201107_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='facebook_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
