# Generated by Django 3.1.3 on 2020-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20201108_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='random_number',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='register_try',
        ),
        migrations.AddField(
            model_name='myusers',
            name='google_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myusers',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
